Models/Cyclist.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Handled.Models
{
    public class Cyclist : IdentityUser
    {
        [Required]
        [Display(Name = "First name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last name")]
        public string LastName { get; set; }
        [Display(Name = "Picture")]
        public string ImagePath { get; set; }
        public int Age { get; set; }
        public double Weight { get; set; }
        public string Height { get; set; }
        public string UserId { get; set; }

        public virtual ICollection<Bicycle> Bicycles { get; set; }
        public virtual ICollection<BicycleRider> BicycleRiders { get; set; }
        public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }
        public virtual ICollection<CyclistEmergencyContact> CyclistEmergencyContacts { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }
    }
}

Controllers/BicyclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Handled.Data;
using Handled.Models;
using Handled.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Handled.Controllers
{
    public class BicyclesController : Controller
    {
        private readonly UserManager<Cyclist> _userManager;
        private readonly ApplicationDbContext _context;

        public BicyclesController(ApplicationDbContext context, UserManager<Cyclist> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        private Task<Cyclist> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Bicycles
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();

            var bicycles = _context.Bicycle.Where(b => b.CyclistId == user.Id);
                return View( await bicycles.ToListAsync());
        }

        // GET: Bicycles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bicycle = await _context.Bicycle
                .Include(b => b.Cyclist)
                .FirstOrDefaultAsync(m => m.BicycleId == id);
            if (bicycle == null)
            {
                return NotFound();
            }

            return View(bicycle);
        }

        // GET: Bicycles/Create
        public IActionResult Create()
        {
            BicyclePhotoUploadViewModel viewbicycle = new BicyclePhotoUploadViewModel();
            //ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email");
            return View(viewbicycle);
        }

        // POST: Bicycles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BicyclePhotoUploadViewModel viewbicycle)
        {
           var user = await GetCurrentUserAsync();
            viewbicycle.Bicycle.CyclistId = user.Id;
            viewbicycle.Bicycle.UserId = user.Id;
            if (ModelState.IsValid)
            {
                if (viewbicycle.ImageFile != null)
                {
                    var fileName = Path.GetFileName(viewbicycle.ImageFile.FileName);
                    Path.GetTempFileName();
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await viewbicycle.ImageFile.CopyToAsync(stream);
                    }

                    viewbicycle.Bicycle.ImagePath = viewbicycle.ImageFile.FileName;
                }
                _context.Add(viewbicycle.Bicycle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email", viewbicycle.Bicycle.Cyclist.Id);
            return View(viewbicycle);
        }

        // GET: Bicycles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            BicyclePhotoUploadViewModel viewbicycle = new BicyclePhotoUploadViewModel();
            viewbicycle.Bicycle = new Bicycle();

            if (id == null)
            {
                return NotFound();
            }

            var bicycle = await _context.Bicycle.FindAsync(id);

            viewbicycle.Bicycle = bicycle;

            if (bicycle == null)
            {
                return NotFound();
            }
            //ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email", viewbicycle.Bicycle.Cyclist.Id);
            return View(viewbicycle);
        }

        // POST: Bicycles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BicyclePhotoUploadViewModel viewbicycle)
        {
            var user = await GetCurrentUserAsync();
            if (id != viewbicycle.Bicycle.BicycleId)
            {
                return NotFound();
            }
                if (ModelState.IsValid)
                {
                    try
                    {
                        viewbicycle.Bicycle.UserId = user.Id;
                        if (viewbicycle.ImageFile != null)
                        {
                            var fileName = Path.GetFileName(viewbicycle.ImageFile.FileName);
                            Path.GetTempFileName();
                            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await viewbicycle.ImageFile.CopyToAsync(stream);
                            }

                            viewbicycle.Bicycle.ImagePath = viewbicycle.ImageFile.FileName;
                        }
                        _context.Update(viewbicycle.Bicycle);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!BicycleExists(viewbicycle.Bicycle.BicycleId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }

                    return RedirectToAction(nameof(Index));
                }
            
            return View(viewbicycle);
        }

        // GET: Bicycles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            BicyclePhotoUploadViewModel viewbicycle = new BicyclePhotoUploadViewModel();
            viewbicycle.Bicycle = new Bicycle();

            if (id == null)
            {
                return NotFound();
            }

            var bicycle = await _context.Bicycle
                .Include(b => b.Cyclist)
                .FirstOrDefaultAsync(m => m.BicycleId == id);

            viewbicycle.Bicycle = bicycle;

            if (bicycle == null)
            {
                return NotFound();
            }

            return View(viewbicycle);
        }

        // POST: Bicycles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, BicyclePhotoUploadViewModel viewbicycle)
        {
            var user = await GetCurrentUserAsync();
            var bicycle = await _context.Bicycle.FindAsync(id);
            var bicyclerider = await _context.BicycleRider.Where(br => br.BicycleId == id).SingleOrDefaultAsync();
            viewbicycle.Bicycle = bicycle;

            if (bicyclerider != null)
            {
                var incident = await _context.Incident.Where(i => i.BicycleRiderId == bicyclerider.BicycleRiderId).SingleOrDefaultAsync();

                if (incident != null && incident.UserId == user.Id)
                {
                    _context.Incident.Remove(incident);
                }
                if (bicyclerider.UserId == user.Id)
                {
                    _context.BicycleRider.Remove(bicyclerider);
                }
            }
            if (bicycle.UserId == user.Id)
            {
                _context.Bicycle.Remove(bicycle);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BicycleExists(int id)
        {
            return _context.Bicycle.Any(e => e.BicycleId == id);
        }
    }
}

Controllers/CyclistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Handled.Data;
using Handled.Models;
using Handled.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Identity;

namespace Handled.Controllers
{
    public class CyclistsController : Controller
    {
        private readonly UserManager<Cyclist> _userManager;
        private readonly ApplicationDbContext _context;

        public CyclistsController(ApplicationDbContext context, UserManager<Cyclist> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<Cyclist> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Cyclists
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var profiles = _context.Cyclist.Where(c => c.Id == user.Id);
            return View(await profiles.ToListAsync());
        }

        // GET: Cyclists/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cyclist = await _context.Cyclist
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cyclist == null)
            {
                return NotFound();
            }

            return View(cyclist);
        }

        // GET: Cyclists/Create
        public IActionResult Create()
        {
            CyclistPhotoUploadViewModel viewcyclist = new CyclistPhotoUploadViewModel();
            return View(viewcyclist);
        }

        // POST: Cyclists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CyclistPhotoUploadViewModel viewcyclist)
        {
            if (ModelState.IsValid)
            {
                if (viewcyclist.ImageFile != null)
                {
                    var fileName = Path.GetFileName(viewcyclist.ImageFile.FileName);
                    Path.GetTempFileName();
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await viewcyclist.ImageFile.CopyToAsync(stream);
                    }

                    viewcyclist.Cyclist.ImagePath = viewcyclist.ImageFile.FileName;
                }
                _context.Add(viewcyclist.Cyclist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewcyclist);
        }

        // GET: Cyclists/Edit/5
        public async Task<IActionResult> Edit(string id)
        {            

            CyclistPhotoUploadViewModel viewcyclist = new CyclistPhotoUploadViewModel();
            viewcyclist.Cyclist = new Cyclist();

            if (id == null)
            {
                return NotFound();
            }

            var cyclist = await _context.Cyclist.FindAsync(id);

            viewcyclist.Cyclist = cyclist;

            if (cyclist == null)
            {
                return NotFound();
            }
            return View(viewcyclist);
        }

        // POST: Cyclists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, CyclistPhotoUploadViewModel viewcyclist)
        {
            if (id != viewcyclist.Cyclist.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   await _userManager.UpdateAsync(viewcyclist.Cyclist);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CyclistExists(viewcyclist.Cyclist.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewcyclist);
        }

        // GET: Cyclists/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cyclist = await _context.Cyclist
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cyclist == null)
            {
                return NotFound();
            }

            return View(cyclist);
        }

        // POST: Cyclists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cyclist = await _context.Cyclist.FindAsync(id);
            _context.Cyclist.Remove(cyclist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CyclistExists(string id)
        {
            return _context.Cyclist.Any(e => e.Id == id);
        }
    }
}

Views/Cyclists/Create.cshtml
@model Handled.Models.ViewModels.CyclistPhotoUploadViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cyclist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create"  enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cyclist.FirstName" class="control-label"></label>
                <input asp-for="Cyclist.FirstName" class="form-control" />
                <span asp-validation-for="Cyclist.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cyclist.LastName" class="control-label"></label>
                <input asp-for="Cyclist.LastName" class="form-control" />
                <span asp-validation-for="Cyclist.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cyclist.Age" class="control-label"></label>
                <input asp-for="Cyclist.Age" class="form-control" />
                <span asp-validation-for="Cyclist.Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cyclist.Weight" class="control-label"></label>
                <input asp-for="Cyclist.Weight" class="form-control" />
                <span asp-validation-for="Cyclist.Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cyclist.Height" class="control-label"></label>
                <input asp-for="Cyclist.Height" class="form-control" />
                <span asp-validation-for="Cyclist.Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="ImageFile" class="control-label"></label>*@
                <label>Photo for profile</label>
                <input asp-for="ImageFile" type="file" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Cyclists/Details.cshtml
@model Handled.Models.Cyclist

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cyclist</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
    </dl>
    <img src="~/images/@Model.ImagePath" class="cyclistDetailImage" />
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Cyclists/Edit.cshtml
@model Handled.Models.ViewModels.CyclistPhotoUploadViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit your profile:</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit"  enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Cyclist.Id" />
            <div class="form-group">
                <label asp-for="Cyclist.FirstName" class="control-label"></label>
                <input asp-for="Cyclist.FirstName" class="form-control" />
                <span asp-validation-for="Cyclist.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cyclist.LastName" class="control-label"></label>
                <input asp-for="Cyclist.LastName" class="form-control" />
                <span asp-validation-for="Cyclist.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cyclist.Email" class="control-label"></label>
                <input asp-for="Cyclist.Email" class="form-control" />
                <span asp-validation-for="Cyclist.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cyclist.Age" class="control-label"></label>
                <input asp-for="Cyclist.Age" class="form-control" />
                <span asp-validation-for="Cyclist.Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cyclist.Weight" class="control-label"></label>
                <input asp-for="Cyclist.Weight" class="form-control" />
                <span asp-validation-for="Cyclist.Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cyclist.Height" class="control-label"></label>
                <input asp-for="Cyclist.Height" class="form-control" />
                <span asp-validation-for="Cyclist.Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Photo for profile</label>
                <input asp-for="ImageFile" type="file" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Cyclists/Index.cshtml
@model IEnumerable<Handled.Models.Cyclist>

@{
    ViewData["Title"] = "Index";
}

<h2>
    Profile
</h2>

<p>
    <a asp-controller="Bicycles" asp-action="Create">New Bike Day!</a>
</p>
<div class="card-columns">
    @foreach (var item in Model)
    {
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">@item.FullName</h1>
            </div>
        </div>
        <div class="card">
            <img class="card-img img-thumbnail" src="~/images/@item.ImagePath" alt="User's profile picture">
        </div>
        <div class="card p-3">
            <blockquote class="blockquote mb-0 card-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                <p>This card would allow the cyclist to post status updates.</p>

                <footer class="blockquote-footer">
                    <small class="text-muted">
                        Someone famous in <cite title="Source Title">Source Title</cite>
                    </small>
                    <small class="text-muted">
                        Last updated 5 minutes ago
                    </small>
                </footer>
            </blockquote>
        </div>

        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Personal Information</h5>
                <p class="card-text">This card has quick reference points to information about the cyclist.</p>
            </div>
        </div>

        <div class="card p-3 text-right">
            <blockquote class="blockquote mb-0">
                <p>Similarly, this card allows the cyclist to share quick tidbits of information: typical cycling routes, known allergies or previous injuries, etc.</p>
            </blockquote>
        </div>
        <div class="card bg-warning text-white text-center p-3">
            <blockquote class="blockquote mb-0">
                <p>Links to My Emergency Contacts</p>
            </blockquote>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Photos</h5>
                <p class="card-text">This space would allow for users to show off images of their bicycles.</p>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Photos</h5>
                <p class="card-text">More space for users to post photos of their bicycles. This would help with laying claim to a bicycle and providing proof of ownership.</p>

            </div>
        </div>

    }
</div>
@*<table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Age)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Weight)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Height)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    <a asp-controller="BicycleRiders" asp-action="Create" asp-route-id="@item.Id">What are you currently riding?</a>
                </td>
                <td>
                    <a asp-controller="Cyclists" asp-action="Edit" asp-route-id="@item.Id">Edit profile</a>
                </td>
            </tr>
    }
        </tbody>
    </table>*@


@*<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Email)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Email)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Age)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Age)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Weight)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Weight)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Height)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Height)
    </dd>
</dl>*@