Models/Bicycle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Handled.Models
{
    public class Bicycle
    {
        [Key]
        public int BicycleId { get; set; }
        [Required]
        [Display(Name = "Vehicle Identification Number (VIN)")]
        public string VIN { get; set; }
        [Display(Name = "Bicycle manufacturer")]
        public string Make { get; set; }
        [Display(Name = "Model")]
        public string Model { get; set; }
        public string Color { get; set; }
        [Display(Name = "Manufactured year")]
        public string ManufactureYear { get; set; }
        [Display(Name = "Photo")]
        public string ImagePath { get; set; }
        [Display(Name = "Cyclist")]
        public string CyclistId { get; set; }
        public Cyclist Cyclist { get; set; }
        public string UserId { get; set; }

        public virtual ICollection<BicycleRider> BicycleRiders { get; set; }
    }
}

Controllers/BicycleRidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Handled.Data;
using Handled.Models;
using Microsoft.AspNetCore.Identity;

namespace Handled.Controllers
{
    public class BicycleRidersController : Controller
    {
        private readonly UserManager<Cyclist> _userManager;
        private readonly ApplicationDbContext _context;

        public BicycleRidersController(ApplicationDbContext context, UserManager<Cyclist> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        private Task<Cyclist> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: BicycleRiders
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var applicationDbContext = _context.BicycleRider
                .Where(b => b.CyclistId == user.Id)
                .Include(b => b.Bicycle)
                .Include(b => b.Cyclist);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BicycleRiders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bicycleRider = await _context.BicycleRider
                .Include(b => b.Bicycle)
                .Include(b => b.Cyclist)
                .FirstOrDefaultAsync(m => m.BicycleRiderId == id);
            if (bicycleRider == null)
            {
                return NotFound();
            }

            return View(bicycleRider);
        }

        // GET: BicycleRiders/Create
        public IActionResult Create()
        {
            ViewData["BicycleId"] = new SelectList(_context.Bicycle, "BicycleId", "Make");
            //ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email");
            return View();
        }

        // POST: BicycleRiders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BicycleRider bicycleRider)
        {
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                bicycleRider.UserId = user.Id;
                bicycleRider.CyclistId = user.Id;
                _context.Add(bicycleRider);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BicycleId"] = new SelectList(_context.Bicycle, "BicycleId", "Make", bicycleRider.BicycleId);
            //ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email", bicycleRider.CyclistId);
            return View(bicycleRider);
        }

        // GET: BicycleRiders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bicycleRider = await _context.BicycleRider.FindAsync(id);
            if (bicycleRider == null)
            {
                return NotFound();
            }
            ViewData["BicycleId"] = new SelectList(_context.Bicycle, "BicycleId", "VIN", bicycleRider.BicycleId);
            ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email", bicycleRider.CyclistId);
            return View(bicycleRider);
        }

        // POST: BicycleRiders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BicycleRiderId,CyclistId,BicycleId")] BicycleRider bicycleRider)
        {
            if (id != bicycleRider.BicycleRiderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bicycleRider);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BicycleRiderExists(bicycleRider.BicycleRiderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BicycleId"] = new SelectList(_context.Bicycle, "BicycleId", "Make", bicycleRider.BicycleId);
            //ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email", bicycleRider.CyclistId);
            return View(bicycleRider);
        }

        // GET: BicycleRiders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bicycleRider = await _context.BicycleRider
                .Include(b => b.Bicycle)
                .Include(b => b.Cyclist)
                .FirstOrDefaultAsync(m => m.BicycleRiderId == id);
            if (bicycleRider == null)
            {
                return NotFound();
            }

            return View(bicycleRider);
        }

        // POST: BicycleRiders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await GetCurrentUserAsync();

            var bicyclerider = await _context.BicycleRider.FindAsync(id);

            //if (bicyclerider != null)
            //{
                var incident = await _context.Incident
                    .Where(i => i.BicycleRiderId == bicyclerider.BicycleRiderId)
                    .FirstOrDefaultAsync();

                if (incident != null)
                     //&& incident.UserId == user.Id
                {
                    _context.Incident
                        .Remove(incident);
                }
            //}
            //if (bicyclerider.UserId == user.Id)
            //{
                _context.BicycleRider.Remove(bicyclerider);
            //}
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BicycleRiderExists(int id)
        {
            return _context.BicycleRider.Any(e => e.BicycleRiderId == id);
        }
    }
}

Controllers/BicyclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Handled.Data;
using Handled.Models;
using Handled.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Handled.Controllers
{
    public class BicyclesController : Controller
    {
        private readonly UserManager<Cyclist> _userManager;
        private readonly ApplicationDbContext _context;

        public BicyclesController(ApplicationDbContext context, UserManager<Cyclist> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        private Task<Cyclist> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Bicycles
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();

            var bicycles = _context.Bicycle.Where(b => b.CyclistId == user.Id);
                return View( await bicycles.ToListAsync());
        }

        // GET: Bicycles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bicycle = await _context.Bicycle
                .Include(b => b.Cyclist)
                .FirstOrDefaultAsync(m => m.BicycleId == id);
            if (bicycle == null)
            {
                return NotFound();
            }

            return View(bicycle);
        }

        // GET: Bicycles/Create
        public IActionResult Create()
        {
            BicyclePhotoUploadViewModel viewbicycle = new BicyclePhotoUploadViewModel();
            //ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email");
            return View(viewbicycle);
        }

        // POST: Bicycles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BicyclePhotoUploadViewModel viewbicycle)
        {
           var user = await GetCurrentUserAsync();
            viewbicycle.Bicycle.CyclistId = user.Id;
            viewbicycle.Bicycle.UserId = user.Id;
            if (ModelState.IsValid)
            {
                if (viewbicycle.ImageFile != null)
                {
                    var fileName = Path.GetFileName(viewbicycle.ImageFile.FileName);
                    Path.GetTempFileName();
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await viewbicycle.ImageFile.CopyToAsync(stream);
                    }

                    viewbicycle.Bicycle.ImagePath = viewbicycle.ImageFile.FileName;
                }
                _context.Add(viewbicycle.Bicycle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email", viewbicycle.Bicycle.Cyclist.Id);
            return View(viewbicycle);
        }

        // GET: Bicycles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            BicyclePhotoUploadViewModel viewbicycle = new BicyclePhotoUploadViewModel();
            viewbicycle.Bicycle = new Bicycle();

            if (id == null)
            {
                return NotFound();
            }

            var bicycle = await _context.Bicycle.FindAsync(id);

            viewbicycle.Bicycle = bicycle;

            if (bicycle == null)
            {
                return NotFound();
            }
            //ViewData["CyclistId"] = new SelectList(_context.Cyclist, "CyclistId", "Email", viewbicycle.Bicycle.Cyclist.Id);
            return View(viewbicycle);
        }

        // POST: Bicycles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BicyclePhotoUploadViewModel viewbicycle)
        {
            var user = await GetCurrentUserAsync();
            if (id != viewbicycle.Bicycle.BicycleId)
            {
                return NotFound();
            }
                if (ModelState.IsValid)
                {
                    try
                    {
                        viewbicycle.Bicycle.UserId = user.Id;
                        if (viewbicycle.ImageFile != null)
                        {
                            var fileName = Path.GetFileName(viewbicycle.ImageFile.FileName);
                            Path.GetTempFileName();
                            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await viewbicycle.ImageFile.CopyToAsync(stream);
                            }

                            viewbicycle.Bicycle.ImagePath = viewbicycle.ImageFile.FileName;
                        }
                        _context.Update(viewbicycle.Bicycle);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!BicycleExists(viewbicycle.Bicycle.BicycleId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }

                    return RedirectToAction(nameof(Index));
                }
            
            return View(viewbicycle);
        }

        // GET: Bicycles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            BicyclePhotoUploadViewModel viewbicycle = new BicyclePhotoUploadViewModel();
            viewbicycle.Bicycle = new Bicycle();

            if (id == null)
            {
                return NotFound();
            }

            var bicycle = await _context.Bicycle
                .Include(b => b.Cyclist)
                .FirstOrDefaultAsync(m => m.BicycleId == id);

            viewbicycle.Bicycle = bicycle;

            if (bicycle == null)
            {
                return NotFound();
            }

            return View(viewbicycle);
        }

        // POST: Bicycles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, BicyclePhotoUploadViewModel viewbicycle)
        {
            var user = await GetCurrentUserAsync();
            var bicycle = await _context.Bicycle.FindAsync(id);
            var bicyclerider = await _context.BicycleRider.Where(br => br.BicycleId == id).SingleOrDefaultAsync();
            viewbicycle.Bicycle = bicycle;

            if (bicyclerider != null)
            {
                var incident = await _context.Incident.Where(i => i.BicycleRiderId == bicyclerider.BicycleRiderId).SingleOrDefaultAsync();

                if (incident != null && incident.UserId == user.Id)
                {
                    _context.Incident.Remove(incident);
                }
                if (bicyclerider.UserId == user.Id)
                {
                    _context.BicycleRider.Remove(bicyclerider);
                }
            }
            if (bicycle.UserId == user.Id)
            {
                _context.Bicycle.Remove(bicycle);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BicycleExists(int id)
        {
            return _context.Bicycle.Any(e => e.BicycleId == id);
        }
    }
}

Views/Bicycles/Create.cshtml
@model Handled.Models.ViewModels.BicyclePhotoUploadViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create a new bicycle:</h1>

<h4>Bicycle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Bicycle.VIN" class="control-label"></label>
                <input asp-for="Bicycle.VIN" class="form-control" />
                <span asp-validation-for="Bicycle.VIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bicycle.Make" class="control-label"></label>
                <input asp-for="Bicycle.Make" class="form-control" />
                <span asp-validation-for="Bicycle.Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bicycle.Model" class="control-label"></label>
                <input asp-for="Bicycle.Model" class="form-control" />
                <span asp-validation-for="Bicycle.Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bicycle.Color" class="control-label"></label>
                <input asp-for="Bicycle.Color" class="form-control" />
                <span asp-validation-for="Bicycle.Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bicycle.ManufactureYear" class="control-label"></label>
                <input asp-for="Bicycle.ManufactureYear" class="form-control" />
                <span asp-validation-for="Bicycle.ManufactureYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Photo of bicycle</label>
                <input asp-for="ImageFile" type="file" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Bicycle.CyclistId" class="control-label"></label>
                <select asp-for="Bicycle.CyclistId" class="form-control" asp-items="ViewBag.CyclistId"></select>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Bicycles/Delete.cshtml
@model Handled.Models.ViewModels.BicyclePhotoUploadViewModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Remove a bicycle from your collection:</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bicycle</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bicycle.VIN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bicycle.VIN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bicycle.Make)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bicycle.Make)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bicycle.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bicycle.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bicycle.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bicycle.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bicycle.ManufactureYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bicycle.ManufactureYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bicycle.Cyclist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bicycle.Cyclist.Email)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Bicycle.BicycleId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Bicycles/Details.cshtml
@model Handled.Models.Bicycle

@{
    ViewData["Title"] = "Details";
}

<h2>Specs:</h2>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VIN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VIN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Make)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Make)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufactureYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cyclist)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cyclist.Email)
        </dd>
    </dl>
    <img src="~/images/@Model.ImagePath" class="bicycleDetailImage" />

</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BicycleId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Bicycles/Edit.cshtml
@model Handled.Models.ViewModels.BicyclePhotoUploadViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit your bicycles specifications:</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit"  enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Bicycle.BicycleId" />
            <div class="form-group">
                <label asp-for="Bicycle.VIN" class="control-label"></label>
                <input asp-for="Bicycle.VIN" class="form-control" />
                <span asp-validation-for="Bicycle.VIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bicycle.Make" class="control-label"></label>
                <input asp-for="Bicycle.Make" class="form-control" />
                <span asp-validation-for="Bicycle.Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bicycle.Model" class="control-label"></label>
                <input asp-for="Bicycle.Model" class="form-control" />
                <span asp-validation-for="Bicycle.Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bicycle.Color" class="control-label"></label>
                <input asp-for="Bicycle.Color" class="form-control" />
                <span asp-validation-for="Bicycle.Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bicycle.ManufactureYear" class="control-label"></label>
                <input asp-for="Bicycle.ManufactureYear" class="form-control" />
                <span asp-validation-for="Bicycle.ManufactureYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Photo for profile</label>
                <input asp-for="ImageFile" type="file" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Bicycle.CyclistId" class="control-label"></label>
                <input asp-for="Bicycle.CyclistId" class="form-control" asp-items="ViewBag.CyclistId">
                <span asp-validation-for="Bicycle.CyclistId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Bicycles/Index.cshtml
@model IEnumerable<Handled.Models.Bicycle>

@{
    ViewData["Title"] = "Index";
}

<h2>The Garage</h2>
<p>Here you will find all your bicycles; those you are currently riding and those gathering dust</p>

<p>
    <a asp-action="Create">New Bike Day!</a>
</p>
<p>
    <a asp-controller="BicycleRiders" asp-action="Index">Tell us what you're currently riding</a>
</p>
    <div class="card-deck w-75">
        @foreach (var item in Model)
        {
           
            <div class="card bg-warning text-white">
                <img class="card-img-top img-fluid" src="~/images/@item.ImagePath" alt="Bicyle image">
                <div class="card-body">
                    <p class="card-text">
                        @Html.DisplayFor(modelItem => item.ManufactureYear)
                        @Html.DisplayFor(modelItem => item.Make)
                        @Html.DisplayFor(modelItem => item.Model)
                    </p>
                    <div class="card-footer">
                  
                        <a asp-action="Details" asp-route-id="@item.BicycleId" class="card-link text-dark">Specs</a>
                        <a asp-action="Delete" asp-route-id="@item.BicycleId" class="card-link text-dark">Remove</a>
                    </div>
                </div>
            </div>
        }
    </div>